---
abstract: 'A Logging role for L<Moose> on L<Log::Syslog::Fast>'
author:
  - 'Thiago Rondon <thiago@nsms.com.br>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Role-Log-Syslog-Fast
requires:
  Log::Syslog::Fast: 0
  Moose::Role: 0
resources:
  bugtracker: http://github.com/maluco/Role-Log-Syslog-Fast/issues
  repository: git://github.com/maluco/Role-Log-Syslog-Fast.git
version: 0.013
